### ISSUE TITLE
Cling jupyter kernel fails when `cling` is a relative path symlink

### ISSUE THREAD

**Issue by lwolfsonkin** [root-project/cling#209]
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/local/Cellar/cling/0.5_1/libexec/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/usr/local/Cellar/cling/0.5_1/libexec/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/Cellar/cling/0.5_1/libexec/share/cling/Jupyter/kernel/clingkernel.py", line 128, in __init__
    raise RuntimeError('Cannot find ' + clingInstDir + '/lib/libclingJupyter.{so,dylib,dll}'))
RuntimeError: Cannot find ../Cellar/cling/0.5_1/lib/libclingJupyter.{so,dylib,dll}
```

The reason for the problem is that the relative path symlink gets reinterpreted as relative from the calling directory, which is not what we want. I was able to fix this locally by replacing:

```python
whichCling = os.readlink(shutil.which('cling'))
```

with

```python
whichCling = os.path.realpath(shutil.which('cling'))
```

which turns the relative symlink into a real path, evaluates an absolute symlink, and leaves normal paths alone.

The actually makes the `OSError` `except` block that follows unnecessary as well.

**Comment by lwolfsonkin** [comment]
The reason `cling` is relative symlinked for me is that I installed it with `brew` on my mac.

**Comment by clouds56** [comment]
Hi I've got trouble install jupyter kernel.

I've run on macOS high Sierra
```
$ brew install cling
$ jupyter kernelspec install --user /usr/local/opt/cling/libexec/share/cling/Jupyter/kernel/cling-cpp1z
$ ln -s ../opt/cling/libexec/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel /usr/local/bin
```
and the jupyter lab keeps complaining
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cling-kernel", line 3, in <module>
    from clingkernel import main
ImportError: No module named clingkernel
```

Did I miss some steps?

**Comment by lwolfsonkin** [comment]
I think you still need to locally pip install `clingkernel` as described [here](https://github.com/root-project/cling/tree/master/tools/Jupyter)

**Comment by clouds56** [comment]
Thanks, it works for me.

And I think it should consider "libexec" as well for the include path here
https://github.com/root-project/cling/blob/master/tools/Jupyter/kernel/clingkernel.py#L148
```
argv = strarr(b"clingJupyter",stdopt, b"-I" + clingInstDir.encode('utf-8') + b"/include/",b"",b"")
```

**Comment by Axel-Naumann** [comment]
Glad to hear it's solved. PR welcome for the libexec part.
