### ISSUE TITLE
Cling build fails at 16%

### ISSUE THREAD

**Issue by jordana309** [root-project/cling#231]
I ran the following script, and got the following output. I am new to playing with compilers, and so I'm sure I made a silly mistake.

Input
```
cd ~/Codes/scr
wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py
chmod +x cpt.py
./cpt.py --check-requirements && ./cpt.py --create-dev-env Debug –with-workdir=../cling-build/
```

Output at break
```
collect2: error: ld returned 1 exit status
tools/clang/utils/TableGen/CMakeFiles/clang-tblgen.dir/build.make:92: recipe for target 'bin/clang-tblgen' failed
make[3]: *** [bin/clang-tblgen] Error 1
CMakeFiles/Makefile2:7693: recipe for target 'tools/clang/utils/TableGen/CMakeFiles/clang-tblgen.dir/all' failed
make[2]: *** [tools/clang/utils/TableGen/CMakeFiles/clang-tblgen.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/SubtargetFeatureInfo.cpp.o
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/TableGen.cpp.o
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/Types.cpp.o
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86DisassemblerTables.cpp.o
[ 16%] Linking CXX static library ../../libLLVMDebugInfoCodeView.a
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o
[ 16%] Built target LLVMDebugInfoCodeView
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86ModRMFilters.cpp.o
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86RecognizableInstr.cpp.o
[ 16%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/CTagsEmitter.cpp.o
[ 16%] Built target obj.llvm-tblgen
CMakeFiles/Makefile2:41738: recipe for target 'tools/cling/tools/driver/CMakeFiles/cling.dir/rule' failed
make[1]: *** [tools/cling/tools/driver/CMakeFiles/cling.dir/rule] Error 2
Makefile:9206: recipe for target 'cling' failed
make: *** [cling] Error 2
subprocess.CalledProcessError: Command 'make -j4 cling' returned non-zero exit status 2
```

I'm have GNU Make 4.1, cmake 3.5.1, and gcc (Ubuntu 5.5.0-12ubuntu1\~16.04) 5.5.0, though I also have gcc-7 (Ubuntu 7.3.0-16ubuntu3~16.04.1) 7.3.0 installed. I just don't know how to activate it if I need that one. If you need any other information, please let me know.

**Comment by Axel-Naumann** [comment]
Most likely there was an additional error message before
```
collect2: error: ld returned 1 exit status
```
Could you check?

It's common to run out of memory, maybe `-j4` is too much. @vgvassilev is there a way to reduce this with cpt.py? Else you can always use the manual approach: https://root.cern.ch/cling-build-instructions

**Comment by jordana309** [comment]
I ran the same arguments for cpt.py, and got the following output (starting with the error you mentioned):

```
collect2: error: ld returned 1 exit status
utils/TableGen/CMakeFiles/llvm-tblgen.dir/build.make:148: recipe for target 'bin/llvm-tblgen' failed
make[3]: *** [bin/llvm-tblgen] Error 1
CMakeFiles/Makefile2:751: recipe for target 'utils/TableGen/CMakeFiles/llvm-tblgen.dir/all' failed
make[2]: *** [utils/TableGen/CMakeFiles/llvm-tblgen.dir/all] Error 2
CMakeFiles/Makefile2:41738: recipe for target 'tools/cling/tools/driver/CMakeFiles/cling.dir/rule' failed
make[1]: *** [tools/cling/tools/driver/CMakeFiles/cling.dir/rule] Error 2
Makefile:9206: recipe for target 'cling' failed
make: *** [cling] Error 2
subprocess.CalledProcessError: Command 'make -j4 cling' returned non-zero exit status 2
```

If that's an out of memory error, I'm confused, because I was watching my memory as it ran, and it didn't even hit 50% of my available memory...what does that error line tell me?

**Comment by Axel-Naumann** [comment]
I said
> Most likely there was an additional error message **before**

Please check, or attach the complete build log.

**Comment by jordana309** [comment]
There was no other error before, and when I ran the script again, it picked up where it left off and returned only the errors above. I fiddled with this a while, and found that I had a customized compiler in my pathdistributed with another software package that I had installed. I also got it to finish building on my machine by opening cpt.py, searching for -j, and I found the following lines:
`exec_subprocess_call('make -j%d %s %s' % (self.cores, targets, flags),
                                 LLVM_OBJ_ROOT)` . A little above that (line 440 when I looked) is the following, which I changed to make self.cores=1 and commented out the check for TRAVIS_OS

```
self.cores = 4
# Travis CI, GCC crashes if more than 4 cores used.
if os.environ.get('TRAVIS_OS_NAME', None):
    self.cores = min(self.cores, 4)
```

And then the kernel wouldn't work, so I have now started over with a Ubuntu install on a new system (switched to my work computer), and we'll see how it goes. I'm running it now. I'll let you know later this week how it went.

**Comment by jordana309** [comment]
Ok, so the build is a no-go. It ate up 30 GB of my hard drive, and even crashed out when I had 8 GB of RAM and 8 GB of swap (the error code 9 or whatever it says when it runs out of memory). So, I instead installed a binary (cling_2018-05-08_ubuntu16.tar.bz2 from [here](https://root.cern.ch/download/cling)). I put it where I wanted it to be installed, and added <cling root>/bin to my PATH. I then tried to install the kernel with `jupyter kernelspec install cling` as stated, and got the following output:

```
Traceback (most recent call last):
  File "/home/jordan/Codes/anaconda/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/jupyter_client/kernelspecapp.py", line 273, in start
    return self.subapp.start()
  File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/jupyter_client/kernelspecapp.py", line 143, in start
    replace=self.replace,
  File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/home/jordan/Codes/anaconda/lib/python3.6/shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'cling'
```

So I poked around, and found a different way to install it: `cd <cling root>/share/cling/Jupyter`, then `jupyter-kernelspec install --user cling-cpp17`, which installed fine, but which gave me the following output when I tried to run it:

```
Failed to run command:
    ['jupyter-cling-kernel', '-f', '/run/user/1000/jupyter/kernel-40b031f2-2bbd-4f67-91d3-4a8d143953e6.json', '--std=c++17']
        PATH='/home/jordan/Codes/anaconda/bin::/home/jordan/Codes/rakudo/build/bin:/home/jordan/Codes/rakudo/build/share/perl6/site/bin:/home/jordan/Codes/sage:/home/jordan/Codes/anaconda/bin:/home/jordan/bin:/home/jordan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jordan/Codes/cling/bin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/home/jordan/Workspace', 'start_new_session': True}
    
[E 22:15:39.537 NotebookApp] Uncaught exception POST /api/sessions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
        yielded = next(result)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/jupyter_client/manager.py", line 259, in start_kernel
        **kw)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/home/jordan/Codes/anaconda/lib/python3.6/site-packages/jupyter_client/launcher.py", line 128, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/home/jordan/Codes/anaconda/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/jordan/Codes/anaconda/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'jupyter-cling-kernel': 'jupyter-cling-kernel'
[W 22:15:39.602 NotebookApp] Unhandled error
[E 22:15:39.603 NotebookApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|194fb086|f519454ecdaa6e95a74e14f418a444d1|1525763763",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "95",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1525839303|23:username-localhost-8888|44:Y2Y3MWY4ZjA2YWU4NGE3YjlhM2M5YTY1OGY3M2IxNmE=|780641fb686148f02044652ee013134f0496c78137c9e0b2ff514b8c34b7b181\"; _xsrf=2|194fb086|f519454ecdaa6e95a74e14f418a444d1|1525763763",
      "Dnt": "1",
      "Connection": "keep-alive"
    }
[E 22:15:39.603 NotebookApp] 500 POST /api/sessions (127.0.0.1) 74.77ms referer=http://localhost:8888/notebooks/Untitled.ipynb
```

I'm a bit at a loss. Any ideas on what I messed up?

**Comment by jordana309** [comment]
Ah. Before trying to install the kernel, I needed to run `pip install -e .` . It installed, and now I just need to figure out how to use it. Sorry for my mess. Hopefully my notes help somebody equally new to all this.

**Comment by Axel-Naumann** [comment]
- Had you sent the build log (as I suggested in https://github.com/root-project/cling/issues/231#issuecomment-386057843 ) I would have been able to help with the linker error.
- Good to hear that the downloaded cling works for you, thanks for confirming. https://github.com/root-project/cling/tree/master/tools/Jupyter shows how to install it.
