### ISSUE TITLE
Segmentation fault when launching cling 0.9 on Ubuntu 22.04

### ISSUE THREAD

**Issue by dimitry-ishenko** [root-project/cling#463]
- [x] Checked for duplicates

### Describe the bug

When I launch cling on Ubuntu 22.04 I get this:
```bash
root@laptop:~# cling
/usr/lib/llvm-9/lib/libLLVM-9.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1f)[0x7f9542a6a3af]
/usr/lib/llvm-9/lib/libLLVM-9.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x22)[0x7f9542a68782]
/usr/lib/llvm-9/lib/libLLVM-9.so.1(+0xa8e7ac)[0x7f9542a6a7ac]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f9541ac1520]
cling(+0x10354b)[0x55b552e8854b]
cling(+0x1104e8)[0x55b552e954e8]
cling(_ZN5cling9CIFactory8createCIEN4llvm9StringRefERKNS_17InvocationOptionsEPKcSt10unique_ptrIN5clang11ASTConsumerESt14default_deleteISA_EERKSt6vectorISt10shared_ptrINS9_19ModuleFileExtensionEESaISH_EE+0xae)[0x55b552e97e4e]
cling(_ZN5cling17IncrementalParserC2EPNS_11InterpreterEPKcRKSt6vectorISt10shared_ptrIN5clang19ModuleFileExtensionEESaIS9_EE+0x1a7)[0x55b552e63b77]
cling(_ZN5cling11InterpreterC1EiPKPKcS2_RKSt6vectorISt10shared_ptrIN5clang19ModuleFileExtensionEESaIS9_EEbPKS0_+0x239)[0x55b552dee9e9]
cling(main+0xc2)[0x55b552dc3912]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f9541aa8d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f9541aa8e40]
cling(_start+0x25)[0x55b552dc3e25]
Stack dump:
0.	Program arguments: cling 
Segmentation fault
```
Running with gdb shows this:
```gdb
root@laptop:~# gdb cling
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cling...
Reading symbols from /usr/lib/debug/.build-id/d7/ac66f0f8fbb62f2c0d272b7b87dd3d8463fe0c.debug...
(gdb) r
Starting program: /usr/bin/cling 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 167910]
[Detaching after vfork from child process 167912]

Program received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_set_length (__n=<optimized out>, this=<optimized out>, this=<optimized out>, __n=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:225
225		traits_type::assign(_M_data()[__n], _CharT());
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_set_length (__n=<optimized out>, this=<optimized out>, this=<optimized out>, 
    __n=<optimized out>) at /usr/include/c++/11/bits/basic_string.h:225
#1  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str=..., this=0x55555577da98) at /usr/include/c++/11/bits/basic_string.h:741
#2  clang::TextDiagnosticPrinter::setPrefix (Value="", this=0x55555577da70) at /usr/lib/llvm-9/include/clang/Frontend/TextDiagnosticPrinter.h:47
#3  (anonymous namespace)::SetupDiagnostics (DiagOpts=..., ExeName="") at ../../lib/Interpreter/./lib/Interpreter/CIFactory.cpp:864
#4  0x00005555556644e8 in (anonymous namespace)::createCIImpl (Buffer=std::unique_ptr<llvm::MemoryBuffer> = {...}, COpts=..., LLVMDir=LLVMDir@entry=0x0, 
    customConsumer=std::unique_ptr<clang::ASTConsumer> = {...}, moduleExtensions=std::vector of length 0, capacity 0, OnlyLex=OnlyLex@entry=false, HasInput=<optimized out>)
    at ../../lib/Interpreter/./lib/Interpreter/CIFactory.cpp:1328
#5  0x0000555555666e4e in cling::CIFactory::createCI (Code=..., Opts=..., LLVMDir=0x0, consumer=..., moduleExtensions=std::vector of length 0, capacity 0)
    at ../../lib/Interpreter/./lib/Interpreter/CIFactory.cpp:1686
#6  0x0000555555632b77 in cling::IncrementalParser::IncrementalParser (this=<optimized out>, interp=<optimized out>, llvmdir=<optimized out>, moduleExtensions=..., 
    this=<optimized out>, interp=<optimized out>, llvmdir=<optimized out>, moduleExtensions=...) at ../../lib/Interpreter/./lib/Interpreter/IncrementalParser.cpp:243
#7  0x00005555555bd9e9 in cling::Interpreter::Interpreter (this=<optimized out>, argc=<optimized out>, argv=<optimized out>, llvmdir=<optimized out>, moduleExtensions=..., 
    noRuntime=<optimized out>, parentInterp=<optimized out>, this=<optimized out>, argc=<optimized out>, argv=<optimized out>, llvmdir=<optimized out>, moduleExtensions=..., 
    noRuntime=<optimized out>, parentInterp=<optimized out>) at ../../lib/Interpreter/./lib/Interpreter/Interpreter.cpp:216
#8  0x0000555555592912 in cling::Interpreter::Interpreter (noRuntime=false, moduleExtensions=..., llvmdir=0x0, argv=0x7fffffffe4d8, argc=1, this=<optimized out>)
    at ./include/cling/Interpreter/Interpreter.h:338
#9  main (argc=1, argv=0x7fffffffe4d8) at ./tools/driver/cling.cpp:79
```

### Expected behavior

I expected something better than the above. Like an interactive shell, where I can enter C++
statements would be nice.

### To Reproduce

1. Launch cling
2. Get slapped in the face with a segfault.

### Setup

1. cling 0.9
2. Ubuntu 22.04
3. I've cloned cling at tag 0.9, debianized it and threw a few patches on top. My clone with build instructions can be found here:

https://salsa.debian.org/dimitry-ishenko/cling

### Additional context

Same exactly identical code compiled for Ubuntu 20.04 runs totally fine. But for some reason it segfaults on 22.04.

**Comment by dimitry-ishenko** [comment]
This seems to be related to building cling with [LTO](https://llvm.org/docs/LinkTimeOptimization.html).
